version: '3'
 
services:
    php:
        build:
            context: ./config/php
        ports:
            - 9000:9000
        volumes:
            - ./www:/srv/www/api
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        links:
            - db
 
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./www:/srv/www/api
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    phpmyadmin:
        image: arm64v8/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - ${IP}:8000:80
        links:
            - db:db

    db:
        image: biarms/mysql:5.7
        ports:
            - ${IP}:3300:3306
        command: "mysqld --init-file /data/application/init.sql"
        volumes:
            - ./data/init.sql:/data/application/init.sql
            - db_data:/var/lib/mysql
            - ./config/db/my.conf:/etc/my.cnf
        environment:
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

volumes:
    db_data:
